;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        kill-sexp
        org-delete-char
        org-end-of-line
        org-force-self-insert
        sp--self-insert-command
        toggle-input-method
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        org-self-insert-command
        ))
